### ISSUE TITLE
Plan for `ErrorKind`?

### ISSUE THREAD

**Issue by MabezDev** [embassy-rs/embedded-io#17]
Is there anything stopping us from copying the `ErrorKind` variants from `std::io`? Do we want to be more conservative? 

I would like to use embedded-io (and currently have a PR open for an embedded-io blanket impl https://github.com/rafalh/rust-fatfs/pull/83) in rust-fatfs, however, the `ErrorKind` situation makes this a bit awkward.

**Comment by Dirbaio** [comment]
done in https://github.com/rust-embedded/embedded-hal/pull/471
